server:
  port: 8086

spring:
  application:
    name: PromotionService

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/promotiondb}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    info:
      enabled: true
  info:
    env:
      enabled: true
app:
  security:
    enabled: false