services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!123
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Tinh2004@", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - user-service
      - order-service
      - cart-service
      - notification-service
    networks:
      - backend

  user-service:
    build:
      context: ./UserService
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - mongo
      - sqlserver   # 👈 THÊM DÒNG NÀY

  product-service:
    build:
      context: ./ProductService
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - backend

  order-service:
    build:
      context: ./OrderService
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    networks:
      - backend

  cart-service:
    build:
      context: ./CartService
    container_name: cart-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    networks:
      - backend

  notification-service:
    build:
      context: ./NotificationService
    container_name: notification-service
    ports:
      - "8089:8089"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_RABBITMQ_VIRTUAL_HOST=/
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge
