server:
  port: 8082

spring:
  application:
    name: UserService
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
        retry:
          enabled: true
          initial-interval: 2000ms
          max-attempts: 3
          multiplier: 1.5
    publisher-confirm-type: correlated
    publisher-returns: true
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
#    connection-timeout: 5000
#    template:
#      retry:
#        enabled: true
#        initial-interval: 2000ms
#        max-attempts: 3

  # Thêm cấu hình CORS
  web:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    info:
      enabled: true
  info:
    env:
      enabled: true

app:
  security:
    enabled: false

jwt:
  secret: your-secret-key-very-long-and-secure
  expiration: 86400000