spring:
  application:
    name: UserService

  datasource:
    url: jdbc:sqlserver://host.docker.internal:1433;databaseName=User;encrypt=false
    username: sa
    password: Tinh2004@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  basic:
    enabled: false

server:
  port: 8082

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
