spring:
  application:
    name: CartService

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AppKTPM;encrypt=false
    username: sa
    password: Tinh2004@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    enabled: false   # ✅ Tắt Eureka hoàn toàn
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
