server:
  port: 8084

spring:
  application:
    name: CartService

  data:
    mongodb:
      uri: ${MONGODB_URI}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      retry:
        enabled: true
        initial-interval: 2000ms
        max-attempts: 3
        multiplier: 1.5
    publisher-confirm-type: correlated
    publisher-returns: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include:  "health,info,metrics"
  endpoint:
    info:
      enabled: true
  info:
    env:
      enabled: true

app:
  security:
    enabled: false
