server:
  port: 8084

spring:
  application:
    name: CartService

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://vinhthai2612:HoVinhThai%40123@cluster.8oclyud.mongodb.net/?retryWrites=true&w=majority&appName=Cluster}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 2000ms
        max-attempts: 3
        multiplier: 1.5
    publisher-confirm-type: correlated
    publisher-returns: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include:  "health,info,metrics"
  endpoint:
    info:
      enabled: true
  info:
    env:
      enabled: true

app:
  security:
    enabled: false
