server:
  port: 8083

spring:
  application:
    name: OrderService

  data:
    mongodb:
      uri: mongodb://mongo:27017/orderservice

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
