server:
  port: 8083

spring:
  application:
    name: OrderService

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  cartservice:
    build: .
    depends_on:
      - mongo

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
