spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: trancongtinh20042004@gmail.com  # ? Thay b?ng email c?a b?n
    password: wltj zyqp kinl rxjz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8089
