spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranngochung19112004@gmail.com
    password: NgocHung19112004@
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8089

