spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: trancongtinh20042004@gmail.com
    password: oksvfmqnejhnogey
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail:
        debug: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 10000
    template:
      exchange: notification-exchange
      routing-key: notification.routing.key
      retry:
        enabled: true
        initial-interval: 3000ms
        max-attempts: 5
        multiplier: 1.5
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        concurrency: 1
        max-concurrency: 5
        auto-startup: true
        startup-timeout: 30000ms
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000ms
          max-interval: 15000ms
          multiplier: 2.0
    cache:
      channel:
        size: 5
        checkout-timeout: 10000
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/notificationdb}

server:
  port: 8089

notification:
  service:
    auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0cmFuY29uZ3RpbmgyMDA0MjAwNEBnbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9BRE1JTiIsInVzZXJJZCI6IjY4MjZkNTNkZjNlYzBjNzljYjZhNmE0MyIsImlhdCI6MTc0NzM3ODE0MiwiZXhwIjoxNzQ5OTcwMTQyfQ._cWLcS1jqrjB2KqtW0X3zpLW4NxE7D1xwUUYqcjXskg
    default-email: fallback@example.com

jwt:
  secret: bXktc2VjdXJlLWtleS1mb3Itand0LTMyLWJ5dGVzISE=