server:
  port: 8085

spring:
  application:
    name: PaymentService
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI}
      connect-timeout: 5000
      socket-timeout: 3000

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      retry:
        enabled: true
        initial-interval: 2000ms
        max-attempts: 3
        multiplier: 1.5
    publisher-confirm-type: correlated
    publisher-returns: true
#    host: rabbitmq
#    port: 5672
#    username: guest
#    password: guest
#    template:
#      retry:
#        enabled: true
#        initial-interval: 2000ms
#        max-attempts: 3
#        multiplier: 1.5
#    publisher-confirm-type: correlated
#    publisher-returns: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

app:
  security:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  info:
    env:
      enabled: true
