server:
  port: 8085

spring:
  application:
    name: PaymentService
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      connect-timeout: 5000
      socket-timeout: 3000
  rabbitmq:
    host: rabbitmq  # Giữ nguyên từ application.yml (có thể thay thành "localhost" nếu cần)
    port: 5672
    username: guest
    password: guest
    template:
      retry:
        enabled: true
        initial-interval: 2000ms
        max-attempts: 3
        multiplier: 1.5
    publisher-confirm-type: correlated
    publisher-returns: true
  websocket:
    path: /ws
    allowed-origins:  # Thêm từ application.properties
      - http://localhost:3000
      - https://tht-store.vercel.app

sepay:
  api-key: ${SEPAY_API_KEY:VEVQTLYOZLWJXJ0NGHUMPI84UBLDZS6TEPKUWCDOKSJFGEMKDV7X9WCNSEQP2IO6}
  client-key: ${SEPAY_CLIENT_KEY:VEVQTLYOZLWJXJ0NGHUMPI84UBLDZS6TEPKUWCDOKSJFGEMKDV7X9WCNSEQP2IO6}
  env: ${SEPAY_ENV:production}
  qr-url: https://qr.sepay.vn/img  # Giữ nguyên từ application.yml (có thể thay thành "https://sepay.vn/qr" nếu cần)
  webhook-url: ${SEPAY_WEBHOOK_URL:https://websitebandogiadung-payment.onrender.com/api/payments/sepay/webhook}
  transaction-timeout: ${TRANSACTION_TIMEOUT:300}
  client-urls: ${CLIENT_URL:https://tht-store.vercel.app,http://localhost:3000}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

app:
  security:
    enabled: false
  services:  # Thêm phần này để lưu trữ URL của các dịch vụ
    order:
      url: https://websitebandogiadung.onrender.com/api/orders
    product:
      url: https://websitebandogiadung.onrender.com/api/products

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  info:
    env:
      enabled: true