server:
  port: 8081

spring:
  application:
    name: ProductService

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  cartservice:
    build: .
    depends_on:
      - mongo

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include:  "health,info,metrics"
  endpoint:
    info:
      enabled: true
  info:
    env:
      enabled: true
