server:
  port: 8081

spring:
  application:
    name: ProductService

  data:
    mongodb:
      uri: ${MONGODB_URI}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "info,health"
