server:
  port: 8081

spring:
  application:
    name: ProductService

  data:
    mongodb:
      uri: mongodb://localhost:27017/productdb

eureka:
  client:
    enabled: false   # ✅ Tắt Eureka hoàn toàn
    register-with-eureka: false
    fetch-registry: false


management:
  endpoints:
    web:
      exposure:
        include:  "health,info,metrics"
  endpoint:
    info:
      enabled: true # Bật endpoint /actuator/info
  info:
    env:
      enabled: true # Bật thông tin môi trường