server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1234

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**,/api/products/categories/**,/api/categories/**
          filters:
            - RemoveRequestHeader=Authorization

        - id: user-service-route
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**
          filters:
            - RemoveRequestHeader=Authorization # Thêm filter để xóa token

        - id: order-service-route
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - RemoveRequestHeader=Authorization

        - id: cart-service-route
          uri: http://cart-service:8084
          predicates:
            - Path=/api/carts/**
          filters:
            - RemoveRequestHeader=Authorization

        - id: notification-service-route
          uri: http://notification-service:8089
          predicates:
            - Path=/api/notifications/**
          filters:
            - RemoveRequestHeader=Authorization

        - id: payment-service-route
          uri: http://payment-service:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - RemoveRequestHeader=Authorization

        - id: promotion-service-route
          uri: http://promotion-service:8086
          predicates:
            - Path=/api/promotions/**
          filters:
            - RemoveRequestHeader=Authorization

      discovery:
        enabled: false

      # Cấu hình CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:5173", "http://localhost:5174"] # Thêm 5174
            allowedMethods: ["*"]
            allowedHeaders: ["*"]
            allowCredentials: true

eureka:
  client:
    enabled: false
    healthcheck:
      enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true