server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1234

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://localhost:8081  # ✅ Chuyển hướng đến ProductService
          predicates:
            - Path=/api/products/**, /api/categories/**  # ✅ Bổ sung /api/categories/**

        - id: user-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
        - id: order-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
        - id: cart-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
