server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1234

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**, /api/categories/**

        - id: user-service-route
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**

        - id: order-service-route
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**

        - id: cart-service-route
          uri: http://cart-service:8084
          predicates:
            - Path=/api/cart/**

        - id: notification-service-route
          uri: http://notification-service:8089
          predicates:
            - Path=/api/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
