server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 1234

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: https://websitebandogiadung-products.onrender.com/api/products/
          predicates:
            - Path=/api/products/**,/api/products/categories/**,/api/categories/**
          # Xóa filter RemoveRequestHeader=Authorization

        - id: user-service-route
          uri: https://websitebandogiadung-users.onrender.com/api/users
          predicates:
            - Path=/api/users/**
          # Xóa filter RemoveRequestHeader=Authorization

        - id: order-service-route
          uri: https://websitebandogiadung-order.onrender.com/api/orders
          predicates:
            - Path=/api/orders/**
          # Xóa filter RemoveRequestHeader=Authorization

        - id: cart-service-route
          uri: https://websitebandogiadung-cart.onrender.com/api/carts/items
          predicates:
            - Path=/api/carts/**
          # Xóa filter RemoveRequestHeader=Authorization

        - id: notification-service-route
          uri: https://websitebandogiadung-notification.onrender.com/api/notifications
          predicates:
            - Path=/api/notifications/**
          # Xóa filter RemoveRequestHeader=Authorization

        - id: payment-service-route
          uri: https://websitebandogiadung-payment.onrender.com/api/payments
          predicates:
            - Path=/api/payments/**
          # Xóa filter RemoveRequestHeader=Authorization

        - id: promotion-service-route
          uri: http://promotion-service:8086
          predicates:
            - Path=/api/promotions/**
          # Xóa filter RemoveRequestHeader=Authorization

      discovery:
        enabled: false

      # Cấu hình CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ["http://localhost:5173", "http://localhost:5174","https://tht-giadungthongminh.vercel.app/"] # Thêm 5174
            allowedMethods: ["*"]
            allowedHeaders: ["*"]
            allowCredentials: true

eureka:
  client:
    enabled: false
    healthcheck:
      enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true